baseURL       = "https://thatold.dev/"
languageCode  = "en-us"
title         = "That Old Dev"
theme         = "risotto"

[module]
  [[module.imports]]
    path    = "github.com/joeroe/risotto"
    version = "v0.4.0"
