name: Build and Deploy That Old Dev

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repo (including any theme submodule, if you added one)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2) Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"

      # 3) Build public/ directory
      - name: Build Hugo site
        run: hugo --minify

      # 4) Deploy public/ to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
